import React, { useState } from 'react';
import { Transaction, TransactionStatus, TransactionType, Account } from '../../types';
import { StorageService, generateUUID } from '../../services/storageService';
import { TransactionService } from '../../services/transactionService';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { X, AlertCircle } from 'lucide-react';

interface PaymentProps {
  tx: Transaction;
  accounts: Account[];
  onClose: () => void;
  onSave: () => void;
}

export const PaymentModal: React.FC<PaymentProps> = ({ tx, accounts, onClose, onSave }) => {
  const [paidValue, setPaidValue] = useState(tx.amount.toString());
  const [paymentDate, setPaymentDate] = useState(new Date().toISOString().split('T')[0]);
  const [scheduleNext, setScheduleNext] = useState(true);
  const [nextDate, setNextDate] = useState('');

  const diff = tx.amount - parseFloat(paidValue || '0');
  const isPartial = diff > 0.01;

  const handleConfirm = async () => {
    const val = parseFloat(paidValue);
    if (!val || val <= 0) return alert("Informe um valor válido.");

    try {
      // 1. Update current transaction
      await TransactionService.update(tx.id, {
        amount: val,
        status: TransactionStatus.PAID,
        paymentDate: paymentDate
      });

      // 2. If partial, schedule residue
      if (isPartial && scheduleNext && nextDate) {
        await TransactionService.create({
          ...tx,
          // id and createdAt will be generated by the API/DB
          amount: diff,
          status: TransactionStatus.PENDING,
          date: nextDate,
          paymentDate: undefined,
          description: `${tx.description} (Resíduo)`
        });
      }

      onSave();
    } catch (error) {
      console.error('Failed to confirm payment:', error);
      alert('Erro ao confirmar liquidação.');
    }
  };

  return (
    <div className="fixed inset-0 z-[120] flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
      <div className="bg-white rounded-[40px] shadow-2xl w-full max-w-sm p-10 animate-[scaleIn_0.2s]">
        <div className="flex justify-between items-center mb-8">
          <h3 className="text-xl font-black uppercase tracking-tight">Dar Baixa</h3>
          <button onClick={onClose}><X size={24} /></button>
        </div>
        <div className="space-y-6">
          <div className="p-4 bg-gray-50 rounded-2xl flex justify-between items-center">
            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Valor Original</p>
            <p className="text-lg font-black tabular-nums">R$ {tx.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <Input label="Liquidação" type="date" value={paymentDate} onChange={e => setPaymentDate(e.target.value)} />
            <Input label="Valor Pago" type="number" step="0.01" value={paidValue} onChange={e => setPaidValue(e.target.value)} autoFocus />
          </div>

          {isPartial && (
            <div className="p-5 border border-blue-100 bg-blue-50/30 rounded-3xl space-y-4 animate-[fadeIn_0.3s]">
              <div className="flex items-center gap-2 text-blue-700 font-black text-[10px] uppercase tracking-widest"><AlertCircle size={14} /> Pagamento Parcial</div>
              <p className="text-xs text-blue-600 font-medium">Restam <b>R$ {diff.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</b>. O que fazer?</p>

              <div className="space-y-2">
                <button type="button" onClick={() => setScheduleNext(true)} className={`w-full p-3 rounded-2xl text-left text-[10px] font-black uppercase tracking-widest border transition-all ${scheduleNext ? 'bg-white border-blue-400 shadow-sm text-blue-600' : 'bg-transparent border-blue-200 text-blue-400'}`}>
                  Agendar resíduo para:
                  {scheduleNext && <input type="date" value={nextDate} onChange={e => setNextDate(e.target.value)} className="w-full mt-2 p-2 border-0 bg-blue-50 rounded-xl text-sm" required />}
                </button>
                <button type="button" onClick={() => setScheduleNext(false)} className={`w-full p-3 rounded-2xl text-left text-[10px] font-black uppercase tracking-widest border transition-all ${!scheduleNext ? 'bg-white border-blue-400 shadow-sm text-blue-600' : 'bg-transparent border-blue-200 text-blue-400'}`}>
                  Ignorar resíduo
                </button>
              </div>
            </div>
          )}

          <Button onClick={handleConfirm} className="w-full h-16 rounded-[24px] bg-emerald-600 hover:bg-emerald-700 text-white border-0">Confirmar Liquidação</Button>
        </div>
      </div>
    </div>
  );
};