"""Add accounts table

Revision ID: 33e6910120cc
Revises: 45d525de7d0d
Create Date: 2026-02-20 21:46:52.476107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e6910120cc'
down_revision: Union[str, None] = '45d525de7d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT', 'CASH', 'INVESTMENT', name='accounttype'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('PF', 'PJ', name='entitytype'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
