"""Initial commit

Revision ID: 45d525de7d0d
Revises: 
Create Date: 2026-02-20 20:51:28.917213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d525de7d0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
    
    # Custom seed data
    import uuid
    from datetime import datetime, timezone
    
    # Pre-calculated hash for "admin123" using bcrypt directly
    hashed_password = "$2b$12$SMxmXEuayxlGNyVTh/5eKut5XzyYWWv7AgjKY3fIIzMg8B5C7/sty"
    user_id = str(uuid.uuid4())
    now_str = datetime.now(timezone.utc).isoformat()
    
    op.execute(
        f"""
        INSERT INTO users (id, name, email, hashed_password, is_active, created_at, updated_at)
        VALUES ('{user_id}', 'Admin User', 'admin@bridge.com', '{hashed_password}', true, '{now_str}', '{now_str}')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email = 'admin@bridge.com'")
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
